AWSTemplateFormatVersion: '2010-09-09'
Description: Root CloudFormation template.

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type for MyFuckingEC2Instance
  AMIId:
    Type: AWS::EC2::Image::Id
    Default: ami-0ac0e4288aa341886
    Description: Amazon Linux 2 AMI ID for MyFuckingEC2Instance
  

Resources:
  MyFuckingEC2Instance: #name of the resource
    Type: AWS::EC2::Instance #type of the resource
    Properties:
      ImageId: 
        Ref: AMIId
      InstanceType: 
        Ref: InstanceType
      Tags:
        - Key: Name
          Value: MyFuckingEC2Instance
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup
        - sg-0adb5f3cc2c454d6e

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MyFuckingEC2Instance
      VpcId: vpc-0e2deb57930ba1d89
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  EC2InstanceId:
    Description: Instance ID returned by Ref
    Value:
      Ref: MyFuckingEC2Instance
  EC2InstancePublicIp:
    Description: Public IP returned by Fn::GetAtt
    Value:
      Fn::GetAtt:
        - MyFuckingEC2Instance
        - PublicIp
  EC2InstancePrivateIp:
    Description: Private IP returned by Fn::GetAtt
    Value: 
      Fn::GetAtt:
        - MyFuckingEC2Instance
        - PrivateIp
  EC2PublicDnsName:
    Description: Public DNS name returned by Fn::GetAtt
    Value: 
      Fn::GetAtt:
        - MyFuckingEC2Instance
        - PublicDnsName
  EC2PrivateDnsName:
    Description: Private DNS name returned by Fn::GetAtt  
    Value: 
      Fn::GetAtt:
        - MyFuckingEC2Instance
        - PrivateDnsName
  EC2AvailabilityZone:
    Description: Availability Zone returned by Fn::GetAtt
    Value: 
      Fn::GetAtt:
        - MyFuckingEC2Instance
        - AvailabilityZone