AWSTemplateFormatVersion: '2010-09-09'
Description: Root CloudFormation template.
Resources:
  MyFuckingEC2Instance: #name of the resource
    Type: AWS::EC2::Instance #type of the resource
    Properties:
      ImageId: ami-0c55b159cbfafe1f0 #Amazon Linux 2 AMI
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: MyEC2Instance
  Outputs:
    EC2InstanceId:
      Description: The ID of the newly created EC2 instance.
      Value:
        Ref: EC2Instance