AWSTemplateFormatVersion: '2010-09-09'
Description: Sample template to create an S3 bucket.
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lmaolmeonguyenkhoinguyenheheheboi 
      Tags:
        - Key: Environment
          Value: Development
Outputs:
  BucketName:
    Description: The name of the newly created S3 bucket.
    Value:
      Ref: MyS3Bucket
