template-file-path: EC2_Nginx.yaml

parameters:
  KeyName: 110326-keypair
  InstanceType: t2.micro
  AMIId: ami-0ac0e4288aa341886
  S3BucketName: cloudformationv2-projectbucket-wxbzxcuixp55
  S3ObjectKey: index.html
  S3AppPrefix: website/

tags: {}