template-file-path: template.yaml
parameters:
  AMIId: ami-0ac0e4288aa341886
  SSHLocation: 0.0.0.0/0
  DBMasterUserPassword: '****'
  DBMasterUsername: admin
  S3AppPrefix: website/
  KeyName: 110326-keypair
  S3BackendObjectKey: backend/demo-api.zip
  VpcId: vpc-0e2deb57930ba1d89
  DBAllocatedStorage: '20'
  PublicSubnetId: subnet-0233c513ba69e7b41
  DBSubnetId2: subnet-07c431a097e7ed2aa
  DBName: appdb
  S3BucketName: cloudformationv2-projectbucket-wxbzxcuixp55
  InstanceType: t2.micro
  DBSubnetId1: subnet-0e306c89fc1d898c2
tags: {}
